# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra_aluno', models.CharField(max_length=10)),
                ('nome_aluno', models.CharField(max_length=100)),
                ('email_aluno', models.CharField(max_length=50)),
                ('celular_aluno', models.CharField(max_length=15)),
                ('sigla_curso', models.CharField(max_length=5)),
            ],
        ),
    ]
